version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/lms
      - static_volume:/lms/staticfiles
      - media_volume:/lms/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.25
    volumes:
      - static_volume:/lms/staticfiles
      - media_volume:/lms/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - web

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/lms
      - static_volume:/lms/staticfiles
      - media_volume:/lms/media
    env_file:
      - .env
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A config beat -l INFO
    volumes:
      - .:/lms
      - static_volume:/lms/staticfiles
      - media_volume:/lms/media
    env_file:
      - .env
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume: 
    