version: '3.8'

services:
  web:
    build: .
    command: python manage.py test
    volumes:
      - .:/lms
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER} && psql -U ${USER} -d ${NAME} -c '\\du'"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.3
    ports:
      - "6380:6379" 