version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/lms
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    profiles:
      - dev

  web-test:
    build: .
    command: python manage.py test
    volumes:
      - .:/lms
    env_file:
      - .env
    depends_on:
      - db
      - redis
    profiles:
      - test

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - PGPASSWORD=${PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=${PASSWORD} pg_isready -U ${USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.3
    ports:
      - "6380:6379"

  celery:
    build: .
    command: celery -A lms worker -l INFO
    volumes:
      - .:/lms
    env_file:
      - .env
    depends_on:
      - redis
      - db
    profiles:
      - dev

volumes:
  postgres_data:
  static_volume:
  media_volume: 
    