version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - habit_bot_network

  nginx:
    image: nginx:1.25
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - habit_bot_network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: habit_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: b20d5fcd
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - habit_bot_network

  redis:
    image: redis:7.2.3
    ports:
      - "6378:6379"
    networks:
      - habit_bot_network

  celery:
    build: .
    command: >
      sh -c "celery -A config worker 
             --broker=redis://redis:6379/0 
             --backend=redis://redis:6379/0 
             -l INFO"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - POSTGRES_DB=habit_bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=b20d5fcd
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env
    depends_on:
      - web
      - redis
    networks:
      - habit_bot_network

  celery-beat:
    build: .
    command: >
      sh -c "celery -A config beat 
             --broker=redis://redis:6379/0 
             --backend=redis://redis:6379/0 
             -l INFO"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - web
      - redis
    networks:
      - habit_bot_network

networks:
  habit_bot_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: