name: Django CI/CD

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Update poetry.lock
      run: poetry lock

    - name: Install Dependencies
      run: poetry install

    - name: Format code with black
      run: |
        poetry run black .

    - name: Check code formatting
      run: |
        poetry run black . --check
    
    - name: Run linter
      run: |
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Sort imports with isort
      run: |
        poetry run isort .

    - name: Check import sorting
      run: |
        poetry run isort . --check-only

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create .env file
      run: |
        echo "SECRET_KEY='django-insecure-test-key'" >> .env
        echo "DEBUG=False" >> .env
        echo "NAME=habit_bot" >> .env
        echo "USER=postgres" >> .env
        echo "PASSWORD=b20d5fcd" >> .env
        echo "HOST=db" >> .env
        echo "PORT=5432" >> .env
        echo "LOCATION=redis://redis:6379/0" >> .env
        echo "TELEGRAM_BOT_TOKEN=test-token" >> .env

    - name: Run tests with Docker Compose
      run: docker compose --profile test up --build --abort-on-container-exit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        debug: true
        script: |
          cd /var/www/habit_bot
          git pull origin main
          docker compose down
          docker compose up -d --build
          